"""Render `.devforge/context/review-brief-<ISSUE-ID>.md`.

Generated by `devforge policy check --diff` when human_review is still
missing. The brief is meant to be handed to an AI agent for an assisted
review pass — but it states explicitly that only `devforge review` run
by a human satisfies the human_review evidence.
"""

from __future__ import annotations

from pathlib import Path

from devforge_ai_cli.core.paths import TEMPLATES_DIR, get_devforge_dir


def _suggested_prompt(issue_id: str) -> str:
    return (
        f"Revise a mudança usando "
        f".devforge/context/review-brief-{issue_id}.md "
        f"e me diga se há riscos antes da aprovação humana."
    )


def suggested_ai_review_prompt(issue_id: str) -> str:
    return _suggested_prompt(issue_id)


def review_brief_path(base: Path, issue_id: str) -> Path:
    return get_devforge_dir(base) / "context" / f"review-brief-{issue_id}.md"


def render_review_brief(
    base: Path,
    issue_id: str,
    policy_check: dict,
) -> Path:
    from jinja2 import Environment, FileSystemLoader

    out = review_brief_path(base, issue_id)
    out.parent.mkdir(parents=True, exist_ok=True)

    env = Environment(
        loader=FileSystemLoader(str(TEMPLATES_DIR)),
        autoescape=False,
        keep_trailing_newline=True,
    )
    tmpl = env.get_template("review-brief.md.j2")
    baseline = policy_check.get("project_prcp_baseline") or policy_check.get("prcp_level") or "Standard"
    effective = policy_check.get("effective_prcp_level") or policy_check.get("prcp_level") or baseline
    out.write_text(
        tmpl.render(
            issue_id=issue_id,
            policy_decision=policy_check.get("decision", "REQUIRE_APPROVAL"),
            project_prcp_baseline=baseline,
            effective_prcp_level=effective,
            reasons=policy_check.get("reasons", []) or [],
            changed_files=policy_check.get("changed_files", []) or [],
            required_evidence=policy_check.get("required_evidence", []) or [],
            evidence_status=policy_check.get("evidence_status", {}) or {},
            evidence_details=policy_check.get("evidence_details", {}) or {},
            review_request_paths=policy_check.get("review_request_paths", []) or [],
            suggested_prompt=_suggested_prompt(issue_id),
        ),
        encoding="utf-8",
    )
    return out
