import json
from datetime import datetime, timezone
from pathlib import Path

from devforge_ai_cli.core.paths import get_devforge_dir


def write_evidence_pack(evidence: dict, base: Path) -> list[str]:
    devforge_dir = get_devforge_dir(base)
    evidence_dir = devforge_dir / "evidence"
    evidence_dir.mkdir(exist_ok=True)

    evidence_id = evidence["evidence_id"]
    created_at = datetime.now(timezone.utc).isoformat()
    generated: list[str] = []

    # ── JSON ──────────────────────────────────────────────────────────────────
    json_path = evidence_dir / f"{evidence_id}.json"
    json_path.write_text(
        json.dumps(
            {
                "evidence_id": evidence_id,
                "issue_id": evidence["issue_id"],
                "status": evidence["status"],
                "policy_decision": evidence["policy_decision"],
                "prcp_level": evidence["prcp_level"],
                "tests_passed": evidence["tests_passed"],
                "human_review_required": evidence["human_review_required"],
                "final_decision": evidence["final_decision"],
                "changed_files": evidence["changed_files"],
                "required_evidence": evidence["required_evidence"],
                "evidence_status": evidence["evidence_status"],
                "missing_evidence": evidence["missing_evidence"],
                "generated_files": [],  # filled after
                "created_at": created_at,
            },
            indent=2,
            ensure_ascii=False,
        ),
        encoding="utf-8",
    )
    generated.append(str(json_path.relative_to(base)))

    # ── Markdown ──────────────────────────────────────────────────────────────
    ev_table_rows = "\n".join(
        f"| {ev} | {status} |"
        for ev, status in evidence["evidence_status"].items()
    )
    changed_files_md = "\n".join(f"- {f}" for f in evidence["changed_files"]) or "- (nenhum)"
    reasons_md = "\n".join(f"- {r}" for r in evidence["reasons"]) or "- (nenhum)"
    required_md = "\n".join(f"- {r}" for r in evidence["required_evidence"]) or "- (nenhum)"
    diff_stat_md = (
        f"```\n{evidence['diff_stat']}\n```" if evidence.get("diff_stat") else "(sem diff detectado)"
    )

    final_decision = evidence["final_decision"]
    if final_decision == "ready_for_pr":
        recommended = "Abrir pull request. Todas as evidências presentes."
    elif final_decision == "pending_human_review":
        recommended = "Solicitar revisão humana antes do merge."
    elif final_decision == "blocked_missing_evidence":
        missing = ", ".join(evidence.get("missing_evidence", []))
        recommended = f"Completar evidências ausentes: {missing}."
    else:
        recommended = "Mudança negada. Revisar antes de prosseguir."

    md_content = f"""\
# Evidence Pack — {evidence_id}

## Summary

- Issue: {evidence['issue_id']}
- Status: {evidence['status']}
- Policy Decision: {evidence['policy_decision']}
- PRCP Level: {evidence['prcp_level']}
- Tests Passed: {evidence['tests_passed']}
- Human Review Required: {evidence['human_review_required']}
- Final Decision: {final_decision}
- Generated: {created_at}

## Changed Files

{changed_files_md}

## Reasons

{reasons_md}

## Required Evidence

{required_md}

## Evidence Status

| Evidence | Status |
|---|---|
{ev_table_rows}

## Diff Summary

{diff_stat_md}

## Recommended Next Action

{recommended}

---

> Generated by DevForge CLI — Governança local-first, revisão humana sempre.
"""
    md_path = evidence_dir / f"{evidence_id}.md"
    md_path.write_text(md_content, encoding="utf-8")
    generated.append(str(md_path.relative_to(base)))

    audit_ref = str((devforge_dir / "audit" / "audit.ndjson").relative_to(base))
    generated.append(audit_ref)

    # Update json with generated_files
    json_data = json.loads(json_path.read_text(encoding="utf-8"))
    json_data["generated_files"] = generated
    json_path.write_text(json.dumps(json_data, indent=2, ensure_ascii=False), encoding="utf-8")

    return generated
